# Site
name: "SMANIWA Blog"
title: "SMANIWA Board Pages"
description: "Mocking up"
#logo: 'assets/images/logo.png'
#favicon: 'assets/images/logo.png'
baseurl: https://smaniwaweb-blog.firebaseapp.com/
#google_analytics: 'UA-46278016-1'
disqus: 'vzrenggamani'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  vzrenggamani:
    name: Rengga Prakoso Nugroho
    display_name: vzrenggamani
    email: me@auruchan.web.id
    web: https://blog.auruchan.web.id
    twitter: https://twitter.com/vzrenggamani
    description: "Ex-OSISMPKSMANIWA CTO"

  Kontributor:
    name: Kontributor Blog SMA Negeri 1 Wonoayu
    display_name: Kontributor Konten
    email: blog@sman1wonoayu.sch.id
    web: https://blog.sman1wonoayu.sch.id
    twitter: sman1wny
    description: Kontributor Konten SMA Negeri 1 Wonoayu | Submission bot
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
